baseURL = "http://example.org/"
languageCode = "en-us"
title = "Î»"
theme = "hugo-tania"
[params]
titleEmoji = "ðŸ¦†"
[params.socialOptions]

[[menu.header]]
name = "Articles"
url = "/posts/"

[[menu.footer]]
name = "RSS"
url = "/index.xml"

